### ISSUE TITLE
Update to 1.19.3 Please

### ISSUE THREAD

**Issue by sternschnaube** [IMS212/LetSleepingDogsLie-Fabric#6]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Let Sleeping Dogs Lie' (letsleepingdogslie) 1.1.1 with any version that is compatible with:
		 - Other constraints that can't be automatically determined
Unmet dependency listing:
	 - Mod 'Let Sleeping Dogs Lie' (letsleepingdogslie) 1.1.1 requires any 8.x version of mod 'Cloth Config v9' (cloth-config), which can't be loaded due to other constraints!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

I use Cloth Config v9.0.94.

**Comment by venaminecraft** [comment]
1.19.3 version from iChun: https://modrinth.com/mod/let-sleeping-dogs-lie/version/LoFumH5i
